config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'reminders#new'

  match 'create' => 'reminder#show', :via => :post

  resource :reminder

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  include ActionView::Helpers::NumberHelper

  def new
    @patients = Patient.all
  end

  def create
    @patient = Patient.find(params[:reminder][:patient_id])
    @msg = params[:user_message]
    @first_name = @patient.first_name
    @last_name = @patient.last_name
    @phone_number = number_to_phone(@patient.phone_number, area_code: true)

    render "show"
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patientmsg</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reminders/_form.html.erb
<%= form_for :reminder, url: reminder_path do |f| %>
  <p>
    <%= f.label :patients %><br>
    <%= f.collection_select :patient_id, @patients.order(:last_name),:id,:last_name%>
  </p>

  <p>
    <%= f.label :message %><br>
    <%= f.text_area :text, placeholder: "Hi there %{first_name} %{last_name}! Is %{phone_number} still the best number to reach you?", name: "user_message" %>
  </p>

  <p>
    <%= f.submit "Submit"%>
  </p>
<% end %>

app/views/reminders/new.html.erb
<h1>Pick a patient from the list to create a message</h1>
<%= render 'form' %>

app/views/reminders/show.html.erb
<p id="message">
  <strong>Message to Patient</strong><br><br>
  <%= @msg % {last_name: @last_name, first_name: @first_name, phone_number: @phone_number} %>
</p>
<%= link_to "Home", root_path %>